### ISSUE TITLE
您好，请问可以提供其他的下载源吗？

### ISSUE THREAD

**Issue by hertz-pj** [AidenHuen/Chinese-Character-Feature-Resource#1]
使用git下载这份数据实在是太慢了，可以提供云盘或者发送这份资源到我的邮箱嘛，十分感谢。
peiji.yang@foxmail.com

**Comment by AidenHuen** [comment]
您好，感谢您的关注，由于资源在学校电脑，目前可能无法发给你。你可以在github上直接下载压缩包，亲测速度还是很快的。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"peiji"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月21日(星期五) 晚上11:06
收件人:&nbsp;"AidenHuen/Chinese-Character-Feature-Resource"<Chinese-Character-Feature-Resource@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[AidenHuen/Chinese-Character-Feature-Resource] 您好，请问可以提供其他的下载源吗？ (#1)




使用git下载这份数据实在是太慢了，可以提供云盘或者发送这份资源到我的邮箱嘛，十分感谢。
 peiji.yang@foxmail.com
